services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      chrome:
        condition: service_healthy

  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://chrome:4444" ]
      interval: 10s
      timeout: 5s
      retries: 3
